spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/trade_db
    username: root
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    root: INFO              # Set root log level (DEBUG, INFO, WARN, ERROR)
    org.springframework: INFO
    org.hibernate.SQL: DEBUG     # Show SQL queries
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE  # Show SQL values
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/app.log      # Optional: log to file

